version: '3.4'

services:
  elastic_master1:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.5.4
    container_name: elastic_master1
    command: >
      bash -c "[ ! -d /usr/share/elasticsearch/plugins/ingest-attachment ] \
        && bin/elasticsearch-plugin install -b ingest-attachment
      /usr/local/bin/docker-entrypoint.sh eswrapper"
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - C:\Data\Elasticsearch:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - esnet

  elastic_master2:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.5.4
    container_name: elastic_master2
    command: >
      bash -c "[ ! -d /usr/share/elasticsearch/plugins/ingest-attachment ] \
        && bin/elasticsearch-plugin install -b ingest-attachment
      /usr/local/bin/docker-entrypoint.sh eswrapper"
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "discovery.zen.ping.unicast.hosts=elastic_master1"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    networks:
      - esnet

  cerebro:
    image: lmenezes/cerebro:latest
    ports:
      - "9000:9000"
    networks:
      - esnet
      
networks:
  esnet:
